# Generated by Django 4.2.11 on 2024-04-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('timestamp', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
